# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

# Define an environment variable
env:
  - SYMFONY_VERSION="3.0.*" DB=mysql

# Update composer
before-install:
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS DAVFOLIO;'  
  - mysql -u root --default-character-set=utf8 DAVFOLIO < src/DavBundle/Resources/BDD/restore.sql

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:update --force

# Run script
script:
  - phpunit

# After a build, send email notification with the build results
notifications:
  email: your_email
